In [ ]:
import numpy as np

In [ ]:
sales_data= np.array([
    [1,150000,200000,250000],
    [2,120000,160000,140000],
    [3,120000,260000,320000],
    [4,180000,240000,280000],
    [5,160000,200000,240000]
])

print("=== Analysis ===")

print("Shape : ",sales_data.shape)

print("Restaurent Yearly income : ",sales_data[:,1:])

print("Total Yearly income : ",np.sum(sales_data[:,1:],axis=0))

print("Minimum monthly income : ",np.min(sales_data[:,1:],axis=1))

print("Maximum monthly income : ",np.max(sales_data[:,1:],axis=1))

print("Average monthly income : ",np.mean(sales_data[:,1:],axis=1))

print("Cumsom monthly income : ",np.cumsum(sales_data[:,1:],axis=1))


=== Analysis ===
Shape :  (5, 4)
Restaurent Yearly income :  [[150000 200000 250000]
 [120000 160000 140000]
 [120000 260000 320000]
 [180000 240000 280000]
 [160000 200000 240000]]
Total Yearly income :  [ 730000 1060000 1230000]
Minimum monthly income :  [150000 120000 120000 180000 160000]
Maximum monthly income :  [250000 160000 320000 280000 240000]
Average monthly income :  [200000.         140000.         233333.33333333 233333.33333333
 200000.        ]
Cumsom monthly income :  [[150000 350000 600000]
 [120000 280000 420000]
 [120000 380000 700000]
 [180000 420000 700000]
 [160000 360000 600000]]


<h2>Vector Calculation</h2>

In [ ]:
Vector1 = np.array([1,2,3,4])
Vector2 = np.array([5,6,7,8])

print("Matrix addition : ",Vector1 + Vector2)

print("Matrix multiplication : ", Vector1* Vector2)

print("Dot Project : ",np.dot(Vector1,Vector2))

## Vectorized

restaurant_type= np.array(['Chineese','Panjabi','Gujarati'])
vectrorized_upper= np.vectorize(str.upper)

print("Restaurent Type : ",vectrorized_upper(restaurant_type))



Matrix addition :  [ 6  8 10 12]
Matrix multiplication :  [ 5 12 21 32]
Dot Project :  70
Restaurent Type :  ['CHINEESE' 'PANJABI' 'GUJARATI']
