<h2>Indexing</h2>

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Indexing : ",arr[2:7])
print("Indexing : ",arr[1:2])
print("Indexing : ",arr[-3])

Indexing :  [3 4 5 6 7]
Indexing :  [2]
Indexing :  8


<h2>Slicing</h2>

In [3]:
arr_2d= np.array([[1,2,3],[4,5,6],[7,8,9]])
print("First Slice : ",arr_2d[1][2])
print("Second Slice : ",arr_2d[1])
print("Thired Slice : ",arr_2d[:,1])

First Slice :  6
Second Slice :  [4 5 6]
Thired Slice :  [2 5 8]


<h2>Shorting</h2>

In [4]:
unsorted = np.array([3,7,5,4,2,9,1,6])
print("Shorted Array : ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[8,1],[6,5]])
print("Shorted Array : ", np.sort(arr_2d_unsorted,axis=1))

Shorted Array :  [1 2 3 4 5 6 7 9]
Shorted Array :  [[1 3]
 [1 8]
 [5 6]]


<h2>Filter</h2>

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_number = numbers[numbers % 2 == 0]
print(even_number)

[2 4 6 8]


<h2>Filter With Mask</h2>

In [6]:
mask = numbers > 5
print(numbers[mask])

[6 7 8 9]


<h2>Where Function</h2>        

In [11]:
indices = np.array([0,2,4])
print(numbers[indices])

where_result = np.where(numbers > 5)
print("Where Condition : ",numbers[where_result])

condition_array= np.where(numbers>5, numbers*2,numbers)
print("Conditional Array : ",condition_array)

[1 3 5]
Where Condition :  [6 7 8 9]
Conditional Array :  [ 1  2  3  4  5 12 14 16 18]


<h2>Merge Two array</h2>

In [12]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([6,7,8,9])

combined = np.concatenate((arr1,arr2))
print("Conbined Array : ",combined)

Conbined Array :  [1 2 3 4 6 7 8 9]


<h2>Compability</h2>

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a.shape == b.shape)

original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))
print("Original Array : ",original)
print("With New Row : ",with_new_row)

new_col = np.array([[7],[8]])

with_new_col = np.hstack((original,new_col))
print("With New Column : ",with_new_col)


True
Original Array :  [[1 2]
 [3 4]]
With New Row :  [[1 2]
 [3 4]
 [5 6]]
With New Column :  [[1 2 7]
 [3 4 8]]


<h2>Delete Element</h2>

In [19]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Deleted Array : ",deleted);

Deleted Array :  [1 2 4 5]
